### PR TITLE
feat: add support for prometheus push gateway

### PR DESCRIPTION
**Pull request by NOBLES5E**
close https://github.com/metrics-rs/metrics/issues/215

### CODE REVIEW

**Comment by tobz** [comment]
Overall, the approach here seems pretty straightforward.

I'm currently coming back off vacation and will need a few days to review this properly.

**Review by tobz — APPROVED** [review]
Overall, this looks good to me.

It would be nice if there was a way to use `hyper` for the push gateway as well to reduce the dependency count.  Out of curiosity, did you try `hyper` before using `reqwest`?  The only thing I can think of that `reqwest` might be handling automatically is something like TLS, but I wonder how hard that'd be to use with pure `hyper`.

I'm happy to merge it as-is, but just curious to hear your thoughts.

**Comment by NOBLES5E** [comment]
@tobz Thanks for your feedback. I tried to use hyper client instead of reqwest, but later found that to deal with https in hyper we need to depend on another crate `hyper_tls`, and

 1. parse the url to see if it is "http" or "https"
 2. parse http response to see if it redirects to https
 3. do the final request
 
I am not confident enough that I have considered all the cases, so I just use reqwest instead..

**Comment by NOBLES5E** [comment]
@tobz I just added an example program using prometheus push gateway for completeness.

**Review by tobz — APPROVED** [review]
Yep, makes sense re: `hyper` vs `reqwest`.  Just wanted to make sure we weren't ignoring a potential smaller change.  Thanks for giving it a try. 👍🏻 

Everything else looks good to me.  I'll merge once the CI passes.

**Comment by tobz** [comment]
@NOBLES5E Thanks again for your contribution! 👍🏻

**Comment by tobz** [comment]
Released as `metrics-exporter-prometheus@v0.6.0`.

**Pull request merged**
