### PR TITLE
metrics-util: Derive Clone for Snapshotter

### PR DESCRIPTION
**Pull request by vojtechkral**

### CODE REVIEW

**Comment by vojtechkral** [comment]
CI failed due to unrelated MSRV woes.

**Review by tobz — APPROVED** [review]
Ugh, yeah, I need to fix that.

Anyways, this is simple enough and looks good to me.

**Comment by vojtechkral** [comment]
Thanks!

**Comment by tobz** [comment]
Released in `metrics-util@v0.17.0`.

Thanks again for your contribution. 🙏🏻

**Pull request merged**
