### PR TITLE
Fix broken prometheus example.

### PR DESCRIPTION
**Pull request by BratSinot**
Related with #187 .

### CODE REVIEW

**Comment by tobz** [comment]
Per my [comment](https://github.com/metrics-rs/metrics/issues/187#issuecomment-814954795) on the issue, this should actually be fixing the runtime enter guard in `PrometheusBuilder::install`.

**Comment by BratSinot** [comment]
> Per my [comment](https://github.com/metrics-rs/metrics/issues/187#issuecomment-814954795) on the issue, this should actually be fixing the runtime enter guard in `PrometheusBuilder::install`.

Oh, yeah. I still can't quite get used to Rust async's.
Saved guard, as @sandrovicente suggests.

**Comment by tobz** [comment]
And just to make sure: does the `prometheus_server` example actually run cleanly now?

**Comment by tobz** [comment]
I checked this, it works.

**Comment by tobz** [comment]
@BratSinot Thanks for your contribution!

**Pull request merged**
