### PR TITLE
More advanced metrics-tracing-context benches

### PR DESCRIPTION
**Pull request by MOZGIII**
This PR adds more advanced context benches.

### CODE REVIEW

**Comment by tobz** [comment]
If you pull in the latest commits from `main`, the tests should pass now.

**Comment by binarylogic** [comment]
cc @MOZGIII on this. Getting the right benches in place will benefit Vector. We just recently ran into another performance regression with v0.13.1.

**Comment by MOZGIII** [comment]
I've updated this PR, should be ready to review/merge.

**Comment by tobz** [comment]
Works for me!

**Pull request merged**
